---
title: "ozdata"
author: "ozdata"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ozdata}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
The package `ozdata` allows seaching and retrieving data from `http://data.gov.au/` and `http://ausmacrodata.org/`.

##Installation
```
install.packages("ozdata")
library(ozdata)
```
Development version from GitHub
```
if (!require(devtools))
  install.packages(devtools)
devtools::install_github("AU-BUGRr/ozdata")
```

##Usage
###get_dataset_from_url()
The function `get_dataset_from_url` allows downloading, unzipping and saving files with .shp and .csv extensions from `data.gov.au`. The first argument passed to function `get_dataset_from_url()` is the URL of the data. If file size is larger than 100 Mb and needs to be dowloaded, you can specify the second argument as `forced=TRUE` to proceed with dowloading.

```
# Save the data URL into variable
url <- paste0("https://datagovau.s3.amazonaws.com/bioregionalassessm",
               "ents/LEB/PED/DATA/Resources/Other/110_Context_statement",
               "NTGAB_Selected_Wetlands/062801f2-dcf9-4a2d-b65b-52f20d4",
               "da721.zip")

# pass variable url to the function and save as an object
y <- get_dataset_from_url(url)
```

###get_ausmacrodata()
The `ausmacrodata.org` contains macroeconomic data from the ABS and RBA. Every ausmacrodata series have unique ID and can be loaded either by using full URL or only series ID. The first argument is either full URL or ID. The subsequent argument specifies in what format data should be returned: `tibble`, `ts` or `xts`, whereas `ts` is a default format for quarterly data and `xts` for daily data.

```
# Load the job vacancies data in New South Wales between 1983-2017
# 'jvnswjvstoq' is a unique ID of this series
dat <- get_ausmacrodata('jvnswjvstoq')

#plot the seris
library(xts)
class(dat)
plot(dat)
```
